CREATE DATABASE PCComponentStore;
GO
USE PCComponentStore;
GO

SET XACT_ABORT ON;
GO

CREATE TABLE dbo.USERS (
	user_id INT IDENTITY(1,1) NOT NULL,
	name NVARCHAR(100) NOT NULL,
	email NVARCHAR(255) NOT NULL,
	password NVARCHAR(255) NOT NULL,
	role NVARCHAR(50) NOT NULL,
	status NVARCHAR(50) NOT NULL,
	phone NVARCHAR(20) NULL,
	address NVARCHAR(255) NULL,
    created_at DATETIME2(0) NOT NULL CONSTRAINT DF_USERS_CREATED_AT DEFAULT SYSUTCDATETIME(),
	CONSTRAINT PK_USERS PRIMARY KEY (user_id),
	CONSTRAINT UQ_USERS_EMAIL UNIQUE (email)
);
GO

CREATE TABLE dbo.CATEGORY (
	category_id INT IDENTITY(1,1) NOT NULL,
	name NVARCHAR(100) NOT NULL,
	description NVARCHAR(MAX) NULL,
	CONSTRAINT PK_CATEGORY PRIMARY KEY (category_id)
);
GO

CREATE TABLE dbo.PROMOTION (
	promotion_id INT IDENTITY(1,1) NOT NULL,
	code NVARCHAR(50) NOT NULL,
	discount_percent DECIMAL(5,2) NOT NULL,
	valid_from DATETIME2(0) NOT NULL,
	valid_to DATETIME2(0) NOT NULL,
	CONSTRAINT PK_PROMOTION PRIMARY KEY (promotion_id),
	CONSTRAINT UQ_PROMOTION_CODE UNIQUE (code)
);
GO

CREATE TABLE dbo.AI_CONSULTATIONS (
	consultation_id INT IDENTITY(1,1) NOT NULL,
	user_id INT NOT NULL,
	user_prompt NVARCHAR(MAX) NOT NULL,
	ai_explanation NVARCHAR(MAX) NULL,
	budget_target INT NULL,
	status NVARCHAR(50) NOT NULL,
	error_message NVARCHAR(500) NULL,
	created_at DATETIME2(0) NOT NULL CONSTRAINT DF_AI_CONSULTATIONS_CREATED_AT DEFAULT SYSUTCDATETIME(),
	CONSTRAINT PK_AI_CONSULTATIONS PRIMARY KEY (consultation_id),
	CONSTRAINT FK_AI_CONSULTATIONS_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id)
);
GO

CREATE TABLE dbo.PRODUCT (
	product_id INT IDENTITY(1,1) NOT NULL,
	category_id INT NOT NULL,
	name NVARCHAR(150) NOT NULL,
	description NVARCHAR(MAX) NULL,
	price DECIMAL(18,2) NOT NULL,
	stock_quantity INT NOT NULL,
	image_url NVARCHAR(500) NULL,
	CONSTRAINT PK_PRODUCT PRIMARY KEY (product_id),
	CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (category_id) REFERENCES dbo.CATEGORY(category_id)
);
GO

CREATE TABLE dbo.PRODUCT_SPEC (
	spec_id INT IDENTITY(1,1) NOT NULL,
	product_id INT NOT NULL,
	spec_name NVARCHAR(100) NOT NULL,
	spec_value NVARCHAR(255) NOT NULL,
	CONSTRAINT PK_PRODUCT_SPEC PRIMARY KEY (spec_id),
	CONSTRAINT FK_PRODUCT_SPEC_PRODUCT FOREIGN KEY (product_id) REFERENCES dbo.PRODUCT(product_id)
);
GO

CREATE TABLE dbo.PRODUCT_BENCHMARK (
	benchmark_id INT IDENTITY(1,1) NOT NULL,
	product_id INT NOT NULL,
	benchmark_type NVARCHAR(MAX) NOT NULL,
	score_value INT NOT NULL,
	CONSTRAINT PK_PRODUCT_BENCHMARK PRIMARY KEY (benchmark_id),
	CONSTRAINT FK_PRODUCT_BENCHMARK_PRODUCT FOREIGN KEY (product_id) REFERENCES dbo.PRODUCT(product_id)
);
GO

CREATE TABLE dbo.COMPATIBILITY_MAP (
	map_id INT IDENTITY(1,1) NOT NULL,
	category_id_a INT NOT NULL,
	category_id_b INT NOT NULL,
	required_spec_name NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_COMPATIBILITY_MAP PRIMARY KEY (map_id),
	CONSTRAINT FK_COMPATIBILITY_MAP_CATEGORY_A FOREIGN KEY (category_id_a) REFERENCES dbo.CATEGORY(category_id),
	CONSTRAINT FK_COMPATIBILITY_MAP_CATEGORY_B FOREIGN KEY (category_id_b) REFERENCES dbo.CATEGORY(category_id)
);
GO

CREATE TABLE dbo.USER_BUILDS (
	user_build_id INT IDENTITY(1,1) NOT NULL,
	user_id INT NOT NULL,
	build_name NVARCHAR(150) NOT NULL,
	total_price DECIMAL(18,2) NOT NULL,
	CONSTRAINT PK_USER_BUILDS PRIMARY KEY (user_build_id),
	CONSTRAINT FK_USER_BUILDS_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id)
);
GO

CREATE TABLE dbo.AI_BUILD_ITEMS (
	item_id INT IDENTITY(1,1) NOT NULL,
	consultation_id INT NOT NULL,
	product_id INT NOT NULL,
	quantity INT NOT NULL,
	selection_reason NVARCHAR(500) NULL,
	status NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_AI_BUILD_ITEMS PRIMARY KEY (item_id),
	CONSTRAINT FK_AI_BUILD_ITEMS_AI_CONSULTATIONS FOREIGN KEY (consultation_id) REFERENCES dbo.AI_CONSULTATIONS(consultation_id),
	CONSTRAINT FK_AI_BUILD_ITEMS_PRODUCT FOREIGN KEY (product_id) REFERENCES dbo.PRODUCT(product_id)
);
GO

CREATE TABLE dbo.USER_BUILD_ITEMS (
	user_build_item_id INT IDENTITY(1,1) NOT NULL,
	user_build_id INT NOT NULL,
	product_id INT NOT NULL,
	quantity INT NOT NULL,
	CONSTRAINT PK_USER_BUILD_ITEMS PRIMARY KEY (user_build_item_id),
	CONSTRAINT FK_USER_BUILD_ITEMS_USER_BUILDS FOREIGN KEY (user_build_id) REFERENCES dbo.USER_BUILDS(user_build_id),
	CONSTRAINT FK_USER_BUILD_ITEMS_PRODUCT FOREIGN KEY (product_id) REFERENCES dbo.PRODUCT(product_id)
);
GO

CREATE TABLE dbo.PC_BUILDS (
	pc_build_id INT IDENTITY(1,1) NOT NULL,
	product_id INT NULL,
	build_name NVARCHAR(150) NOT NULL,
	CONSTRAINT PK_PC_BUILDS PRIMARY KEY (pc_build_id),
    CONSTRAINT FK_PC_BUILDS_PRODUCT FOREIGN KEY (product_id) REFERENCES dbo.PRODUCT(product_id)
);
GO

CREATE TABLE dbo.PC_BUILD_ITEMS (
	pc_build_item_id INT IDENTITY(1,1) NOT NULL,
	pc_build_id INT NOT NULL,
	product_id INT NOT NULL,
	quantity INT NOT NULL,
	CONSTRAINT PK_PC_BUILD_ITEMS PRIMARY KEY (pc_build_item_id),
	CONSTRAINT FK_PC_BUILD_ITEMS_PC_BUILDS FOREIGN KEY (pc_build_id) REFERENCES dbo.PC_BUILDS(pc_build_id),
	CONSTRAINT FK_PC_BUILD_ITEMS_PRODUCT FOREIGN KEY (product_id) REFERENCES dbo.PRODUCT(product_id)
);
GO

CREATE TABLE dbo.CART (
	cart_id INT IDENTITY(1,1) NOT NULL,
	user_id INT NOT NULL,
	created_at DATETIME2(0) NOT NULL CONSTRAINT DF_CART_CREATED_AT DEFAULT SYSUTCDATETIME(),
	CONSTRAINT PK_CART PRIMARY KEY (cart_id),
	CONSTRAINT FK_CART_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id)
);
GO

CREATE TABLE dbo.CART_ITEM (
	cart_item_id INT IDENTITY(1,1) NOT NULL,
	cart_id INT NOT NULL,
	product_id INT NULL,
	user_build_id INT NULL,
	quantity INT NOT NULL,
	CONSTRAINT PK_CART_ITEM PRIMARY KEY (cart_item_id),
	CONSTRAINT FK_CART_ITEM_CART FOREIGN KEY (cart_id) REFERENCES dbo.CART(cart_id),
	CONSTRAINT FK_CART_ITEM_PRODUCT FOREIGN KEY (product_id) REFERENCES dbo.PRODUCT(product_id),
	CONSTRAINT FK_CART_ITEM_USER_BUILDS FOREIGN KEY (user_build_id) REFERENCES dbo.USER_BUILDS(user_build_id),
	CONSTRAINT CK_CART_ITEM_TARGET CHECK (
		(CASE WHEN product_id IS NULL THEN 0 ELSE 1 END) +
		(CASE WHEN user_build_id IS NULL THEN 0 ELSE 1 END) = 1
	)
);
GO

CREATE TABLE dbo.[ORDER] (
	order_id INT IDENTITY(1,1) NOT NULL,
    order_date DATETIME2(0) NOT NULL,
	status NVARCHAR(50) NOT NULL,
	total_amount DECIMAL(18,2) NOT NULL,
	user_id INT NOT NULL,
	shipping_address NVARCHAR(255) NULL,
	promotion_id INT NULL,
	CONSTRAINT PK_ORDER PRIMARY KEY (order_id),
	CONSTRAINT FK_ORDER_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id),
	CONSTRAINT FK_ORDER_PROMOTION FOREIGN KEY (promotion_id) REFERENCES dbo.PROMOTION(promotion_id)
);
GO

CREATE TABLE dbo.ORDER_DETAIL (
	order_detail_id INT IDENTITY(1,1) NOT NULL,
	order_id INT NOT NULL,
	product_id INT NOT NULL,
	quantity INT NOT NULL,
	price DECIMAL(18,2) NOT NULL,
    user_build_id INT NULL,
	CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY (order_detail_id),
	CONSTRAINT FK_ORDER_DETAIL_ORDER FOREIGN KEY (order_id) REFERENCES dbo.[ORDER](order_id),
	CONSTRAINT FK_ORDER_DETAIL_PRODUCT FOREIGN KEY (product_id) REFERENCES dbo.PRODUCT(product_id),
    CONSTRAINT FK_ORDER_DETAIL_USER_BUILDS FOREIGN KEY (user_build_id) REFERENCES dbo.USER_BUILDS(user_build_id)
);
GO

CREATE TABLE dbo.PAYMENT (
	payment_id INT IDENTITY(1,1) NOT NULL,
	order_id INT NOT NULL,
    order_date DATETIME2(0) NOT NULL,
    payment_status NVARCHAR(50) NOT NULL,
	total_amount DECIMAL(18,2) NOT NULL,
	payment_method NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_PAYMENT PRIMARY KEY (payment_id),
	CONSTRAINT FK_PAYMENT_ORDER FOREIGN KEY (order_id) REFERENCES dbo.[ORDER](order_id)
);
GO

CREATE TABLE dbo.STAFF_BUILD_REQUESTS (
	request_id INT IDENTITY(1,1) NOT NULL,
	user_id INT NOT NULL,
	staff_id INT NULL,
	customer_note NVARCHAR(1000) NULL,
	budget_range INT NULL,
	status NVARCHAR(50) NOT NULL,
    user_build_id INT NULL,
	created_at DATETIME2(0) NOT NULL CONSTRAINT DF_STAFF_BUILD_REQUESTS_CREATED_AT DEFAULT SYSUTCDATETIME(),
	updated_at DATETIME2(0) NULL,
	CONSTRAINT PK_STAFF_BUILD_REQUESTS PRIMARY KEY (request_id),
	CONSTRAINT FK_STAFF_BUILD_REQUESTS_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id),
	CONSTRAINT FK_STAFF_BUILD_REQUESTS_STAFF FOREIGN KEY (staff_id) REFERENCES dbo.USERS(user_id),
	CONSTRAINT FK_STAFF_BUILD_REQUESTS_USER_BUILDS FOREIGN KEY (user_build_id) REFERENCES dbo.USER_BUILDS(user_build_id)
);
GO

CREATE TABLE dbo.INSTALLMENT_PLANS (
	plan_id INT IDENTITY(1,1) NOT NULL,
	order_id INT NOT NULL,
	total_amount DECIMAL(18,2) NOT NULL,
	down_payment DECIMAL(18,2) NOT NULL,
	total_months INT NOT NULL,
	monthly_amount DECIMAL(18,2) NOT NULL,
	interest_rate DECIMAL(5,2) NOT NULL,
	status NVARCHAR(50) NOT NULL,
	created_at DATETIME2(0) NOT NULL CONSTRAINT DF_INSTALLMENT_PLANS_CREATED_AT DEFAULT SYSUTCDATETIME(),
	CONSTRAINT PK_INSTALLMENT_PLANS PRIMARY KEY (plan_id),
	CONSTRAINT FK_INSTALLMENT_PLANS_ORDER FOREIGN KEY (order_id) REFERENCES dbo.[ORDER](order_id)
);
GO

CREATE TABLE dbo.INSTALLMENT_DETAILS (
	installment_detail_id INT IDENTITY(1,1) NOT NULL,
	plan_id INT NOT NULL,
	installment_number INT NOT NULL,
	due_date DATETIME2(0) NOT NULL,
	amount_to_pay DECIMAL(18,2) NOT NULL,
	paid_date DATETIME2(0) NULL,
	status NVARCHAR(50) NOT NULL,
    payment_method NVARCHAR(50) NULL,
	CONSTRAINT PK_INSTALLMENT_DETAILS PRIMARY KEY (installment_detail_id),
	CONSTRAINT FK_INSTALLMENT_DETAILS_INSTALLMENT_PLANS FOREIGN KEY (plan_id) REFERENCES dbo.INSTALLMENT_PLANS(plan_id)
);
GO
